/** Centroids derived from Natural Earth 110m (public domain). */
export interface CountryCentroid {
  code: string
  name: string
  longitude: number
  latitude: number
}

export const COUNTRY_CENTROIDS: CountryCentroid[] = [
  { code: "AF", name: "Afghanistan", longitude: 67.7864, latitude: 34.7912 },
  { code: "AL", name: "Albania", longitude: 20.0867, latitude: 41.2455 },
  { code: "DZ", name: "Algeria", longitude: 3.2081, latitude: 29.703 },
  { code: "AO", name: "Angola", longitude: 17.457, latitude: -11.0129 },
  { code: "AQ", name: "Antarctica", longitude: -3.0269, latitude: -73.0033 },
  { code: "AR", name: "Argentina", longitude: -65.1536, latitude: -37.0792 },
  { code: "AM", name: "Armenia", longitude: 45.2475, latitude: 40.0073 },
  { code: "AU", name: "Australia", longitude: 133.2777, latitude: -23.7663 },
  { code: "AT", name: "Austria", longitude: 13.3875, latitude: 47.6314 },
  { code: "AZ", name: "Azerbaijan", longitude: 47.4351, latitude: 40.3297 },
  { code: "BS", name: "Bahamas", longitude: -77.9112, latitude: 24.436 },
  { code: "BD", name: "Bangladesh", longitude: 90.5524, latitude: 23.4377 },
  { code: "BY", name: "Belarus", longitude: 28.2222, latitude: 53.3109 },
  { code: "BE", name: "Belgium", longitude: 4.4691, latitude: 50.6196 },
  { code: "BZ", name: "Belize", longitude: -88.6034, latitude: 17.3966 },
  { code: "BJ", name: "Benin", longitude: 2.3121, latitude: 9.9563 },
  { code: "BT", name: "Bhutan", longitude: 90.525, latitude: 27.4425 },
  { code: "BO", name: "Bolivia", longitude: -64.0386, latitude: -16.4279 },
  { code: "BA", name: "Bosnia and Herz.", longitude: 17.8393, latitude: 44.226 },
  { code: "BW", name: "Botswana", longitude: 24.3441, latitude: -22.4865 },
  { code: "BR", name: "Brazil", longitude: -56.9438, latitude: -9.5371 },
  { code: "BN", name: "Brunei", longitude: 114.9339, latitude: 4.6431 },
  { code: "BG", name: "Bulgaria", longitude: 24.7625, latitude: 42.844 },
  { code: "BF", name: "Burkina Faso", longitude: -1.8246, latitude: 12.1572 },
  { code: "BI", name: "Burundi", longitude: 30.0067, latitude: -3.3021 },
  { code: "KH", name: "Cambodia", longitude: 105.0396, latitude: 12.6697 },
  { code: "CM", name: "Cameroon", longitude: 13.1465, latitude: 6.8071 },
  { code: "CA", name: "Canada", longitude: -90.6245, latitude: 56.4298 },
  { code: "CF", name: "Central African Rep.", longitude: 20.5937, latitude: 6.3116 },
  { code: "TD", name: "Chad", longitude: 17.8931, latitude: 12.8802 },
  { code: "CL", name: "Chile", longitude: -71.4684, latitude: -38.3364 },
  { code: "CN", name: "China", longitude: 105.7794, latitude: 37.285 },
  { code: "CO", name: "Colombia", longitude: -72.7113, latitude: 4.5234 },
  { code: "CG", name: "Congo", longitude: 14.8537, latitude: -1.0124 },
  { code: "CR", name: "Costa Rica", longitude: -84.208, latitude: 9.8295 },
  { code: "HR", name: "Croatia", longitude: 16.3788, latitude: 44.8626 },
  { code: "CU", name: "Cuba", longitude: -79.6713, latitude: 21.6871 },
  { code: "CY", name: "Cyprus", longitude: 33.2808, latitude: 35.0164 },
  { code: "CZ", name: "Czech Rep.", longitude: 15.8725, latitude: 49.7396 },
  { code: "CI", name: "C\u00f4te d'Ivoire", longitude: -6.3081, latitude: 7.8943 },
  { code: "CD", name: "Dem. Rep. Congo", longitude: 22.949, latitude: -3.8313 },
  { code: "KP", name: "Dem. Rep. Korea", longitude: 127.2503, latitude: 39.8262 },
  { code: "DK", name: "Denmark", longitude: 9.6051, latitude: 56.3541 },
  { code: "DJ", name: "Djibouti", longitude: 42.5343, latitude: 11.7474 },
  { code: "DO", name: "Dominican Rep.", longitude: -70.4448, latitude: 18.7532 },
  { code: "EC", name: "Ecuador", longitude: -78.8086, latitude: -1.6834 },
  { code: "EG", name: "Egypt", longitude: 31.433, latitude: 28.2127 },
  { code: "SV", name: "El Salvador", longitude: -88.8971, latitude: 13.8247 },
  { code: "GQ", name: "Eq. Guinea", longitude: 10.1399, latitude: 1.4736 },
  { code: "ER", name: "Eritrea", longitude: 39.7053, latitude: 14.7228 },
  { code: "EE", name: "Estonia", longitude: 25.7972, latitude: 58.5511 },
  { code: "ET", name: "Ethiopia", longitude: 39.0612, latitude: 9.0003 },
  { code: "FK", name: "Falkland Is.", longitude: -59.4056, latitude: -51.7222 },
  { code: "FJ", name: "Fiji", longitude: 178.005, latitude: -17.7727 },
  { code: "FI", name: "Finland", longitude: 25.6956, latitude: 65.3801 },
  { code: "TF", name: "Fr. S. Antarctic Lands", longitude: 69.5266, latitude: -49.1803 },
  { code: "FR", name: "France", longitude: 3.2386, latitude: 46.9523 },
  { code: "GA", name: "Gabon", longitude: 11.9119, latitude: -0.4241 },
  { code: "GM", name: "Gambia", longitude: -15.1921, latitude: 13.4953 },
  { code: "GE", name: "Georgia", longitude: 43.5118, latitude: 42.2073 },
  { code: "DE", name: "Germany", longitude: 10.631, latitude: 50.9968 },
  { code: "GH", name: "Ghana", longitude: -1.0121, latitude: 8.1767 },
  { code: "GR", name: "Greece", longitude: 23.1425, latitude: 39.7596 },
  { code: "GL", name: "Greenland", longitude: -40.9877, latitude: 74.0829 },
  { code: "GT", name: "Guatemala", longitude: -90.2122, latitude: 15.5603 },
  { code: "GN", name: "Guinea", longitude: -10.9452, latitude: 10.3874 },
  { code: "GW", name: "Guinea-Bissau", longitude: -15.1327, latitude: 11.9565 },
  { code: "GY", name: "Guyana", longitude: -58.9588, latitude: 4.5477 },
  { code: "HT", name: "Haiti", longitude: -72.7521, latitude: 18.7959 },
  { code: "HN", name: "Honduras", longitude: -86.3644, latitude: 14.7418 },
  { code: "HU", name: "Hungary", longitude: 19.1502, latitude: 47.4329 },
  { code: "IS", name: "Iceland", longitude: -19.5164, latitude: 65.216 },
  { code: "IN", name: "India", longitude: 83.4864, latitude: 23.9339 },
  { code: "ID", name: "Indonesia", longitude: 121.5622, latitude: -2.1054 },
  { code: "IR", name: "Iran", longitude: 53.4092, latitude: 33.3488 },
  { code: "IQ", name: "Iraq", longitude: 44.5782, latitude: 33.4827 },
  { code: "IE", name: "Ireland", longitude: -7.8504, latitude: 53.5035 },
  { code: "IL", name: "Israel", longitude: 35.1774, latitude: 32.1353 },
  { code: "IT", name: "Italy", longitude: 12.6602, latitude: 43.0281 },
  { code: "JM", name: "Jamaica", longitude: -77.3259, latitude: 18.1575 },
  { code: "JP", name: "Japan", longitude: 135.8321, latitude: 35.6241 },
  { code: "JO", name: "Jordan", longitude: 36.7121, latitude: 31.0624 },
  { code: "KZ", name: "Kazakhstan", longitude: 65.0532, latitude: 47.2462 },
  { code: "KE", name: "Kenya", longitude: 37.7854, latitude: 1.2753 },
  { code: "KR", name: "Korea", longitude: 127.5392, latitude: 36.6591 },
  { code: "KO", name: "Kosovo", longitude: 20.9754, latitude: 42.5805 },
  { code: "KW", name: "Kuwait", longitude: 47.7135, latitude: 29.2569 },
  { code: "KG", name: "Kyrgyzstan", longitude: 74.0654, latitude: 41.3372 },
  { code: "LA", name: "Lao PDR", longitude: 103.5905, latitude: 18.397 },
  { code: "LV", name: "Latvia", longitude: 24.8284, latitude: 56.8283 },
  { code: "LB", name: "Lebanon", longitude: 35.8547, latitude: 33.8503 },
  { code: "LS", name: "Lesotho", longitude: 28.3151, latitude: -29.642 },
  { code: "LR", name: "Liberia", longitude: -9.1698, latitude: 6.7181 },
  { code: "LY", name: "Libya", longitude: 16.4862, latitude: 28.5946 },
  { code: "LT", name: "Lithuania", longitude: 23.8789, latitude: 55.1779 },
  { code: "LU", name: "Luxembourg", longitude: 5.9711, latitude: 49.7594 },
  { code: "MK", name: "Macedonia", longitude: 21.6442, latitude: 41.633 },
  { code: "MG", name: "Madagascar", longitude: 46.936, latitude: -18.0861 },
  { code: "MW", name: "Malawi", longitude: 34.1109, latitude: -13.0505 },
  { code: "MY", name: "Malaysia", longitude: 114.6814, latitude: 3.6659 },
  { code: "ML", name: "Mali", longitude: -5.7259, latitude: 14.1014 },
  { code: "MR", name: "Mauritania", longitude: -12.3029, latitude: 18.7743 },
  { code: "MX", name: "Mexico", longitude: -103.0479, latitude: 23.8233 },
  { code: "MD", name: "Moldova", longitude: 28.5415, latitude: 47.0015 },
  { code: "MN", name: "Mongolia", longitude: 104.8129, latitude: 47.1762 },
  { code: "ME", name: "Montenegro", longitude: 19.4099, latitude: 42.7504 },
  { code: "MA", name: "Morocco", longitude: -9.5315, latitude: 28.6506 },
  { code: "MZ", name: "Mozambique", longitude: 34.8695, latitude: -17.9967 },
  { code: "MM", name: "Myanmar", longitude: 97.1105, latitude: 19.9945 },
  { code: "CN", name: "N. Cyprus", longitude: 33.4729, latitude: 35.1798 },
  { code: "NA", name: "Namibia", longitude: 17.8827, latitude: -21.4863 },
  { code: "NP", name: "Nepal", longitude: 84.3968, latitude: 28.2243 },
  { code: "NL", name: "Netherlands", longitude: 5.5483, latitude: 52.0546 },
  { code: "NC", name: "New Caledonia", longitude: 165.4893, latitude: -21.1858 },
  { code: "NZ", name: "New Zealand", longitude: 175.4412, latitude: -38.1438 },
  { code: "NI", name: "Nicaragua", longitude: -85.0038, latitude: 13.1208 },
  { code: "NE", name: "Niger", longitude: 8.6302, latitude: 15.3487 },
  { code: "NG", name: "Nigeria", longitude: 8.4477, latitude: 9.7925 },
  { code: "NO", name: "Norway", longitude: 17.8207, latitude: 66.164 },
  { code: "OM", name: "Oman", longitude: 56.6003, latitude: 20.8138 },
  { code: "PK", name: "Pakistan", longitude: 69.3144, latitude: 30.718 },
  { code: "PS", name: "Palestine", longitude: 35.2214, latitude: 31.8487 },
  { code: "PA", name: "Panama", longitude: -80.3753, latitude: 8.4924 },
  { code: "PG", name: "Papua New Guinea", longitude: 146.3714, latitude: -7.9285 },
  { code: "PY", name: "Paraguay", longitude: -57.5513, latitude: -23.3996 },
  { code: "PE", name: "Peru", longitude: -74.1376, latitude: -7.7992 },
  { code: "PH", name: "Philippines", longitude: 121.7997, latitude: 15.28 },
  { code: "PL", name: "Poland", longitude: 19.3846, latitude: 51.6955 },
  { code: "PT", name: "Portugal", longitude: -8.0075, latitude: 39.6979 },
  { code: "PR", name: "Puerto Rico", longitude: -66.4524, latitude: 18.2461 },
  { code: "QA", name: "Qatar", longitude: 51.194, latitude: 25.3199 },
  { code: "RO", name: "Romania", longitude: 25.1175, latitude: 45.8653 },
  { code: "RU", name: "Russia", longitude: 91.2457, latitude: 59.302 },
  { code: "RW", name: "Rwanda", longitude: 29.8437, latitude: -2.046 },
  { code: "SS", name: "S. Sudan", longitude: 30.0806, latitude: 8.0824 },
  { code: "SA", name: "Saudi Arabia", longitude: 43.7092, latitude: 23.9693 },
  { code: "SN", name: "Senegal", longitude: -14.5421, latitude: 13.8841 },
  { code: "RS", name: "Serbia", longitude: 20.9866, latitude: 43.7837 },
  { code: "SL", name: "Sierra Leone", longitude: -11.6287, latitude: 8.5891 },
  { code: "SK", name: "Slovakia", longitude: 19.2516, latitude: 48.7538 },
  { code: "SI", name: "Slovenia", longitude: 15.0653, latitude: 46.0834 },
  { code: "SB", name: "Solomon Is.", longitude: 159.0679, latitude: -7.8833 },
  { code: "SO", name: "Somalia", longitude: 46.9905, latitude: 6.6502 },
  { code: "SL", name: "Somaliland", longitude: 46.0136, latitude: 10.3477 },
  { code: "ZA", name: "South Africa", longitude: 24.823, latitude: -28.6042 },
  { code: "ES", name: "Spain", longitude: -4.3907, latitude: 40.2368 },
  { code: "LK", name: "Sri Lanka", longitude: 80.7611, latitude: 7.6435 },
  { code: "SD", name: "Sudan", longitude: 29.4003, latitude: 12.9782 },
  { code: "SR", name: "Suriname", longitude: -55.9242, latitude: 3.7528 },
  { code: "SZ", name: "Swaziland", longitude: 31.3736, latitude: -26.3889 },
  { code: "SE", name: "Sweden", longitude: 16.7052, latitude: 62.839 },
  { code: "CH", name: "Switzerland", longitude: 8.2505, latitude: 46.7652 },
  { code: "SY", name: "Syria", longitude: 38.036, latitude: 35.2399 },
  { code: "TW", name: "Taiwan", longitude: 121.021, latitude: 23.7948 },
  { code: "TJ", name: "Tajikistan", longitude: 70.8611, latitude: 38.5471 },
  { code: "TZ", name: "Tanzania", longitude: 34.3521, latitude: -6.6309 },
  { code: "TH", name: "Thailand", longitude: 100.5892, latitude: 13.1634 },
  { code: "TL", name: "Timor-Leste", longitude: 125.9992, latitude: -8.7308 },
  { code: "TG", name: "Togo", longitude: 0.8681, latitude: 8.7674 },
  { code: "TT", name: "Trinidad and Tobago", longitude: -61.4279, latitude: 10.4386 },
  { code: "TN", name: "Tunisia", longitude: 9.8535, latitude: 34.1404 },
  { code: "TR", name: "Turkey", longitude: 36.5985, latitude: 38.4246 },
  { code: "TM", name: "Turkmenistan", longitude: 58.5693, latitude: 39.2838 },
  { code: "UG", name: "Uganda", longitude: 31.9191, latitude: 1.3435 },
  { code: "UA", name: "Ukraine", longitude: 30.6398, latitude: 48.4264 },
  { code: "AE", name: "United Arab Emirates", longitude: 54.3703, latitude: 24.193 },
  { code: "GB", name: "United Kingdom", longitude: -3.0844, latitude: 53.9072 },
  { code: "US", name: "United States", longitude: -90.225, latitude: 38.228 },
  { code: "UY", name: "Uruguay", longitude: -56.0643, latitude: -32.8216 },
  { code: "UZ", name: "Uzbekistan", longitude: 65.4651, latitude: 41.1497 },
  { code: "VU", name: "Vanuatu", longitude: 166.9085, latitude: -15.3294 },
  { code: "VE", name: "Venezuela", longitude: -66.9188, latitude: 7.2356 },
  { code: "VN", name: "Vietnam", longitude: 105.976, latitude: 16.8499 },
  { code: "EH", name: "W. Sahara", longitude: -12.1519, latitude: 24.6711 },
  { code: "YE", name: "Yemen", longitude: 46.3429, latitude: 15.4308 },
  { code: "ZM", name: "Zambia", longitude: 27.932, latitude: -12.9098 },
  { code: "ZW", name: "Zimbabwe", longitude: 29.6162, latitude: -18.7763 },
]

const BY_CODE = new Map(COUNTRY_CENTROIDS.map((c) => [c.code.toUpperCase(), c]))
const BY_NAME = new Map<string, CountryCentroid>()

const NAME_ALIASES: Record<string, string> = {
  "afghanistan": "AF",
  "albania": "AL",
  "algeria": "DZ",
  "angola": "AO",
  "antarctica": "AQ",
  "arab republic of egypt": "EG",
  "argentina": "AR",
  "argentine republic": "AR",
  "armenia": "AM",
  "australia": "AU",
  "austria": "AT",
  "azerbaijan": "AZ",
  "bahamas": "BS",
  "bahamas, the": "BS",
  "bangladesh": "BD",
  "belarus": "BY",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bhutan": "BT",
  "bolivarian republic of venezuela": "VE",
  "bolivia": "BO",
  "bosnia and herz.": "BA",
  "bosnia and herzegovina": "BA",
  "botswana": "BW",
  "brazil": "BR",
  "britain": "GB",
  "brunei": "BN",
  "brunei darussalam": "BN",
  "bulgaria": "BG",
  "burkina faso": "BF",
  "burma": "MM",
  "burundi": "BI",
  "cabo verde": "CV",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "cape verde": "CV",
  "car": "CF",
  "central african rep.": "CF",
  "central african republic": "CF",
  "chad": "TD",
  "chile": "CL",
  "china": "CN",
  "co-operative republic of guyana": "GY",
  "colombia": "CO",
  "commonwealth of australia": "AU",
  "commonwealth of puerto rico": "PR",
  "commonwealth of the bahamas": "BS",
  "congo": "CG",
  "congo, democratic republic of the": "CD",
  "congo, republic of the": "CG",
  "costa rica": "CR",
  "cote d'ivoire": "CI",
  "croatia": "HR",
  "cuba": "CU",
  "cyprus": "CY",
  "czech rep.": "CZ",
  "czech republic": "CZ",
  "czechia": "CZ",
  "c\u00f4te d'ivoire": "CI",
  "c\u00f4te d\u2019ivoire": "CI",
  "dem. rep. congo": "CD",
  "dem. rep. korea": "KP",
  "democratic people's republic of korea": "KP",
  "democratic republic of the congo": "CD",
  "democratic republic of timor-leste": "TL",
  "democratic socialist republic of sri lanka": "LK",
  "denmark": "DK",
  "djibouti": "DJ",
  "dominican rep.": "DO",
  "dominican republic": "DO",
  "dprk": "KP",
  "dr congo": "CD",
  "drc": "CD",
  "east timor": "TL",
  "ecuador": "EC",
  "egypt": "EG",
  "el salvador": "SV",
  "eq. guinea": "GQ",
  "equatorial guinea": "GQ",
  "eritrea": "ER",
  "estonia": "EE",
  "eswatini": "SZ",
  "ethiopia": "ET",
  "falkland is.": "FK",
  "falkland islands": "FK",
  "federal democratic republic of ethiopia": "ET",
  "federal republic of germany": "DE",
  "federal republic of nigeria": "NG",
  "federal republic of somalia": "SO",
  "federative republic of brazil": "BR",
  "fiji": "FJ",
  "finland": "FI",
  "former yugoslav republic of macedonia": "MK",
  "fr. s. and antarctic lands": "TF",
  "fr. s. antarctic lands": "TF",
  "france": "FR",
  "french republic": "FR",
  "french southern and antarctic lands": "TF",
  "gabon": "GA",
  "gabonese republic": "GA",
  "gambia": "GM",
  "gambia, the": "GM",
  "gaza": "PS",
  "georgia": "GE",
  "germany": "DE",
  "ghana": "GH",
  "grand duchy of luxembourg": "LU",
  "great britain": "GB",
  "greece": "GR",
  "greenland": "GL",
  "guatemala": "GT",
  "guinea": "GN",
  "guinea bissau": "GW",
  "guinea-bissau": "GW",
  "guyana": "GY",
  "haiti": "HT",
  "hashemite kingdom of jordan": "JO",
  "hellenic republic": "GR",
  "holland": "NL",
  "holy see": "VA",
  "honduras": "HN",
  "hong kong": "HK",
  "hungary": "HU",
  "iceland": "IS",
  "independent state of papua new guinea": "PG",
  "india": "IN",
  "indonesia": "ID",
  "iran": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "islamic republic of iran": "IR",
  "islamic republic of mauritania": "MR",
  "islamic republic of pakistan": "PK",
  "islamic state of afghanistan": "AF",
  "israel": "IL",
  "italian republic": "IT",
  "italy": "IT",
  "ivory coast": "CI",
  "jamaica": "JM",
  "japan": "JP",
  "jordan": "JO",
  "kazakhstan": "KZ",
  "kenya": "KE",
  "kingdom of belgium": "BE",
  "kingdom of bhutan": "BT",
  "kingdom of cambodia": "KH",
  "kingdom of denmark": "DK",
  "kingdom of lesotho": "LS",
  "kingdom of morocco": "MA",
  "kingdom of norway": "NO",
  "kingdom of saudi arabia": "SA",
  "kingdom of spain": "ES",
  "kingdom of swaziland": "SZ",
  "kingdom of sweden": "SE",
  "kingdom of thailand": "TH",
  "kingdom of the netherlands": "NL",
  "korea": "KR",
  "korea, north": "KP",
  "korea, south": "KR",
  "kosovo": "KO",
  "kuwait": "KW",
  "kyrgyz republic": "KG",
  "kyrgyzstan": "KG",
  "lao pdr": "LA",
  "lao people's democratic republic": "LA",
  "laos": "LA",
  "latvia": "LV",
  "lebanese republic": "LB",
  "lebanon": "LB",
  "lesotho": "LS",
  "liberia": "LR",
  "libya": "LY",
  "lithuania": "LT",
  "luxembourg": "LU",
  "macao": "MO",
  "macau": "MO",
  "macedonia": "MK",
  "madagascar": "MG",
  "malawi": "MW",
  "malaysia": "MY",
  "mali": "ML",
  "mauritania": "MR",
  "mexico": "MX",
  "moldova": "MD",
  "mongolia": "MN",
  "montenegro": "ME",
  "morocco": "MA",
  "mozambique": "MZ",
  "myanmar": "MM",
  "n. cyprus": "CN",
  "namibia": "NA",
  "negara brunei darussalam": "BN",
  "nepal": "NP",
  "netherlands": "NL",
  "new caledonia": "NC",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "north korea": "KP",
  "north macedonia": "MK",
  "northern cyprus": "CN",
  "norway": "NO",
  "oman": "OM",
  "oriental republic of uruguay": "UY",
  "pakistan": "PK",
  "palestine": "PS",
  "panama": "PA",
  "papua new guinea": "PG",
  "paraguay": "PY",
  "people's democratic republic of algeria": "DZ",
  "people's republic of angola": "AO",
  "people's republic of bangladesh": "BD",
  "people's republic of china": "CN",
  "peru": "PE",
  "philippines": "PH",
  "plurinational state of bolivia": "BO",
  "poland": "PL",
  "portugal": "PT",
  "portuguese republic": "PT",
  "puerto rico": "PR",
  "qatar": "QA",
  "republic of albania": "AL",
  "republic of armenia": "AM",
  "republic of austria": "AT",
  "republic of azerbaijan": "AZ",
  "republic of belarus": "BY",
  "republic of benin": "BJ",
  "republic of botswana": "BW",
  "republic of bulgaria": "BG",
  "republic of burundi": "BI",
  "republic of cameroon": "CM",
  "republic of chad": "TD",
  "republic of chile": "CL",
  "republic of colombia": "CO",
  "republic of congo": "CG",
  "republic of costa rica": "CR",
  "republic of croatia": "HR",
  "republic of cuba": "CU",
  "republic of cyprus": "CY",
  "republic of djibouti": "DJ",
  "republic of ecuador": "EC",
  "republic of el salvador": "SV",
  "republic of equatorial guinea": "GQ",
  "republic of estonia": "EE",
  "republic of fiji": "FJ",
  "republic of finland": "FI",
  "republic of ghana": "GH",
  "republic of guatemala": "GT",
  "republic of guinea": "GN",
  "republic of guinea-bissau": "GW",
  "republic of haiti": "HT",
  "republic of honduras": "HN",
  "republic of hungary": "HU",
  "republic of iceland": "IS",
  "republic of india": "IN",
  "republic of indonesia": "ID",
  "republic of iraq": "IQ",
  "republic of ivory coast": "CI",
  "republic of kazakhstan": "KZ",
  "republic of kenya": "KE",
  "republic of korea": "KR",
  "republic of kosovo": "KO",
  "republic of latvia": "LV",
  "republic of liberia": "LR",
  "republic of lithuania": "LT",
  "republic of madagascar": "MG",
  "republic of malawi": "MW",
  "republic of mali": "ML",
  "republic of moldova": "MD",
  "republic of mozambique": "MZ",
  "republic of namibia": "NA",
  "republic of nicaragua": "NI",
  "republic of niger": "NE",
  "republic of panama": "PA",
  "republic of paraguay": "PY",
  "republic of peru": "PE",
  "republic of poland": "PL",
  "republic of rwanda": "RW",
  "republic of senegal": "SN",
  "republic of serbia": "RS",
  "republic of sierra leone": "SL",
  "republic of slovenia": "SI",
  "republic of somaliland": "SL",
  "republic of south africa": "ZA",
  "republic of south sudan": "SS",
  "republic of suriname": "SR",
  "republic of tajikistan": "TJ",
  "republic of the gambia": "GM",
  "republic of the philippines": "PH",
  "republic of the sudan": "SD",
  "republic of the union of myanmar": "MM",
  "republic of trinidad and tobago": "TT",
  "republic of tunisia": "TN",
  "republic of turkey": "TR",
  "republic of uganda": "UG",
  "republic of uzbekistan": "UZ",
  "republic of vanuatu": "VU",
  "republic of yemen": "YE",
  "republic of zambia": "ZM",
  "republic of zimbabwe": "ZW",
  "romania": "RO",
  "russia": "RU",
  "russian federation": "RU",
  "rwanda": "RW",
  "s. sudan": "SS",
  "sahrawi arab democratic republic": "EH",
  "saudi arabia": "SA",
  "senegal": "SN",
  "serbia": "RS",
  "sierra leone": "SL",
  "slovak republic": "SK",
  "slovakia": "SK",
  "slovenia": "SI",
  "socialist republic of vietnam": "VN",
  "solomon is.": "SB",
  "solomon islands": "SB",
  "somalia": "SO",
  "somaliland": "SL",
  "south africa": "ZA",
  "south korea": "KR",
  "south sudan": "SS",
  "spain": "ES",
  "sri lanka": "LK",
  "state of eritrea": "ER",
  "state of israel": "IL",
  "state of kuwait": "KW",
  "state of qatar": "QA",
  "sudan": "SD",
  "sultanate of oman": "OM",
  "suriname": "SR",
  "swaziland": "SZ",
  "sweden": "SE",
  "swiss confederation": "CH",
  "switzerland": "CH",
  "syria": "SY",
  "syrian arab republic": "SY",
  "taiwan": "TW",
  "tajikistan": "TJ",
  "tanzania": "TZ",
  "territory of the french southern and antarctic lands": "TF",
  "thailand": "TH",
  "the bahamas": "BS",
  "the gambia": "GM",
  "timor-leste": "TL",
  "togo": "TG",
  "togolese republic": "TG",
  "trinidad and tobago": "TT",
  "tunisia": "TN",
  "turkey": "TR",
  "turkish republic of northern cyprus": "CN",
  "turkmenistan": "TM",
  "u.s.": "US",
  "u.s.a.": "US",
  "uae": "AE",
  "uganda": "UG",
  "uk": "GB",
  "ukraine": "UA",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  "united kingdom of great britain and northern ireland": "GB",
  "united mexican states": "MX",
  "united republic of tanzania": "TZ",
  "united states": "US",
  "united states of america": "US",
  "uruguay": "UY",
  "usa": "US",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "vatican": "VA",
  "venezuela": "VE",
  "viet nam": "VN",
  "vietnam": "VN",
  "w. sahara": "EH",
  "west bank": "PS",
  "west bank and gaza": "PS",
  "western sahara": "EH",
  "yemen": "YE",
  "zambia": "ZM",
  "zimbabwe": "ZW",
}

function norm(value: string): string {
  return value.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
}

for (const country of COUNTRY_CENTROIDS) {
  BY_NAME.set(norm(country.name), country)
}

export function centroidByCode(code: string | undefined | null): CountryCentroid | undefined {
  if (!code) return undefined
  return BY_CODE.get(code.trim().toUpperCase())
}

export function centroidByName(name: string | undefined | null): CountryCentroid | undefined {
  if (!name) return undefined
  const key = norm(name)
  const direct = BY_NAME.get(key)
  if (direct) return direct
  const alias = NAME_ALIASES[key]
  if (alias) return BY_CODE.get(alias) ?? BY_NAME.get(norm(alias))
  return undefined
}

export function resolveCentroid(codeOrName: string | undefined | null): CountryCentroid | undefined {
  return centroidByCode(codeOrName) ?? centroidByName(codeOrName)
}

